### ISSUE TITLE
Get List of all Markets with symbol

### ISSUE THREAD

**Issue by sakib1361** [bmresearch/Solnet.Mango#83]
**Current Problem**
While developing a seperate application, the User should only interact with symbols instead of market address. 

**Possible Solution**
Parse all market info with address like serum provides. 

**Describe alternatives you've considered**
I tried to look into the source code of mango ui (V3). Somewhere in the system, there must be a way to convert the Symbol name to market Name. But couldnt find a clear list of markets with symbols.

**Comment by murlokito** [comment]
I have added the `ids.json` that is used in the mango-client-v3 for this specific purpose, it only features the data used for the mainnet mango group.

You can either fetch the `MangoGroup` and you can find this data under `MangoGroup.Config` or you can get the `MangoGroupConfig` using [this](https://github.com/bmresearch/Solnet.Mango/blob/master/Solnet.Mango/MangoUtils.cs#L34), I believe these would be helpful for such a case?

**Comment by sakib1361** [comment]
That solves the problem. Thanks a lot.
